config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :orders
  resources :digital_products
  resources :physical_products
  resources :products
  resources :profiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/digital_product.rb
class DigitalProduct < ApplicationRecord
  has_one_attached :image
  belongs_to :product
end

app/controllers/digital_products_controller.rb
class DigitalProductsController < ApplicationController
  before_action :set_digital_product, only: [:show, :edit, :update, :destroy]
  before_action :set_product, only: [:edit, :new, :create]

  # GET /digital_products
  # GET /digital_products.json
  def index
    @digital_products = DigitalProduct.all
  end

  # GET /digital_products/1
  # GET /digital_products/1.json
  def show
  end

  # GET /digital_products/new
  def new
    @digital_product = DigitalProduct.new
  end

  # GET /digital_products/1/edit
  def edit
  end

  # POST /digital_products
  # POST /digital_products.json
  def create
    @digital_product = DigitalProduct.new(digital_product_params)

    respond_to do |format|
      if @digital_product.save
        format.html { redirect_to @digital_product, notice: 'Digital product was successfully created.' }
        format.json { render :show, status: :created, location: @digital_product }
      else
        format.html { render :new }
        format.json { render json: @digital_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /digital_products/1
  # PATCH/PUT /digital_products/1.json
  def update
    respond_to do |format|
      if @digital_product.update(digital_product_params)
        format.html { redirect_to @digital_product, notice: 'Digital product was successfully updated.' }
        format.json { render :show, status: :ok, location: @digital_product }
      else
        format.html { render :edit }
        format.json { render json: @digital_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /digital_products/1
  # DELETE /digital_products/1.json
  def destroy
    @digital_product.destroy
    respond_to do |format|
      format.html { redirect_to digital_products_url, notice: 'Digital product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_digital_product
      @digital_product = DigitalProduct.find(params[:id])
    end

    def set_product
      @products = Product.pluck :name, :id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def digital_product_params
      params.require(:digital_product).permit(:product_id, :image)
    end
end

app/helpers/digital_products_helper.rb
module DigitalProductsHelper
end

app/views/digital_products/_form.html.erb
<%= form_with(model: digital_product, local: true) do |form| %>
  <% if digital_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(digital_product.errors.count, "error") %> prohibited this digital_product from being saved:</h2>

      <ul>
      <% digital_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= form.label :product %>
      <%= form.select :product_id, options_for_select(@products), prompt: "Select product" %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/digital_products/edit.html.erb
<h1>Editing Digital Product</h1>

<%= render 'form', digital_product: @digital_product %>

<%= link_to 'Show', @digital_product %> |
<%= link_to 'Back', digital_products_path %>

app/views/digital_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Digital Products</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @digital_products.each do |digital_product| %>
      <tr>
        <td><%= digital_product.product %></td>
        <td><%= link_to 'Show', digital_product %></td>
        <td><%= link_to 'Edit', edit_digital_product_path(digital_product) %></td>
        <td><%= link_to 'Destroy', digital_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Digital Product', new_digital_product_path %>

app/views/digital_products/new.html.erb
<h1>New Digital Product</h1>

<%= render 'form', digital_product: @digital_product %>

<%= link_to 'Back', digital_products_path %>

app/views/digital_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @digital_product.product %>
</p>

<%= link_to 'Edit', edit_digital_product_path(@digital_product) %> |
<%= link_to 'Back', digital_products_path %>