config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :orders
  resources :digital_products
  resources :physical_products
  resources :products
  resources :profiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/physical_product.rb
class PhysicalProduct < ApplicationRecord
  has_many_attached :images
  belongs_to :product
end

app/controllers/physical_products_controller.rb
class PhysicalProductsController < ApplicationController
  before_action :set_physical_product, only: [:show, :edit, :update, :destroy]
  before_action :set_product, only: [:edit, :new, :create]

  # GET /physical_products
  # GET /physical_products.json
  def index
    @physical_products = PhysicalProduct.all
  end

  # GET /physical_products/1
  # GET /physical_products/1.json
  def show
  end

  # GET /physical_products/new
  def new
    @physical_product = PhysicalProduct.new
  end

  # GET /physical_products/1/edit
  def edit
  end

  # POST /physical_products
  # POST /physical_products.json
  def create
    @physical_product = PhysicalProduct.new(physical_product_params)

    respond_to do |format|
      if @physical_product.save
        format.html { redirect_to @physical_product, notice: 'Physical product was successfully created.' }
        format.json { render :show, status: :created, location: @physical_product }
      else
        format.html { render :new }
        format.json { render json: @physical_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physical_products/1
  # PATCH/PUT /physical_products/1.json
  def update
    respond_to do |format|
      if @physical_product.update(physical_product_params)
        format.html { redirect_to @physical_product, notice: 'Physical product was successfully updated.' }
        format.json { render :show, status: :ok, location: @physical_product }
      else
        format.html { render :edit }
        format.json { render json: @physical_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physical_products/1
  # DELETE /physical_products/1.json
  def destroy
    @physical_product.destroy
    respond_to do |format|
      format.html { redirect_to physical_products_url, notice: 'Physical product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physical_product
      @physical_product = PhysicalProduct.find(params[:id])
    end

    def set_product
      @products = Product.pluck :name, :id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def physical_product_params
      params.require(:physical_product).permit(:product_id, images: [])
    end
end

app/helpers/physical_products_helper.rb
module PhysicalProductsHelper
end

app/views/physical_products/_form.html.erb
<%= form_with(model: physical_product, local: true) do |form| %>
  <% if physical_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(physical_product.errors.count, "error") %> prohibited this physical_product from being saved:</h2>

      <ul>
      <% physical_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= form.label :product %>
      <%= form.select :product_id, options_for_select(@products), prompt: "Select product" %>
  </div>
  
  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/physical_products/edit.html.erb
<h1>Editing Physical Product</h1>

<%= render 'form', physical_product: @physical_product %>

<%= link_to 'Show', @physical_product %> |
<%= link_to 'Back', physical_products_path %>

app/views/physical_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Physical Products</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @physical_products.each do |physical_product| %>
      <tr>
        <td><%= physical_product.product %></td>
        <td><%= link_to 'Show', physical_product %></td>
        <td><%= link_to 'Edit', edit_physical_product_path(physical_product) %></td>
        <td><%= link_to 'Destroy', physical_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Physical Product', new_physical_product_path %>

app/views/physical_products/new.html.erb
<h1>New Physical Product</h1>

<%= render 'form', physical_product: @physical_product %>

<%= link_to 'Back', physical_products_path %>

app/views/physical_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @physical_product.product %>
</p>

<%= link_to 'Edit', edit_physical_product_path(@physical_product) %> |
<%= link_to 'Back', physical_products_path %>